*** PaperGPT (baseado no trabalho magnífico de Andrej Karpathy - https://www.youtube.com/watch?v=kCc8FmEb1nY)

In [1]:
!wget http://www.glaucoreis.com.br/gsreis.txt

--2024-01-24 17:11:59--  http://www.glaucoreis.com.br/gsreis.txt
Resolving www.glaucoreis.com.br (www.glaucoreis.com.br)... 187.45.193.219
Connecting to www.glaucoreis.com.br (www.glaucoreis.com.br)|187.45.193.219|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 464691 (454K) [text/plain]
Saving to: ‘gsreis.txt’

gsreis.txt          100%[===================>] 453,80K  --.-KB/s    in 0,1s    

2024-01-24 17:12:01 (3,61 MB/s) - ‘gsreis.txt’ saved [464691/464691]



In [33]:
#leio todo o texto 
with open('gsreis.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [34]:
print("tamanho do texto: ", len(text))

tamanho do texto:  441545


In [128]:
# Vamos observar um pedacinho dele 
print(text[:2000])

Expoentes da ciência como Stephen Hawking† Bill Gates e Elon Musk expressaram sua preocupação com a IA forte aquela que propõe simular o pensamento humano Porque eles teriam estas preocupações Será que a IA poderia se rebelar Coloquei entre aspas porque rebelar aqui tem um sentido mais amplo do que dominar o mundo Poderia cometer algum erro absurdo que comprometesse a vida talvez ativar uma arma nuclear inadvertidamente ou qualquer uma das inúmeras possibilidades apontadas pela ficção científica No filme Eu Robo estrelado por Will Smith um belíssimo discurso é feito pelo teórico criador na IA no filme Alfred Lanning em uma palestra: Tivemos alguns fantasmas na máquina Trechos de códigos randômicos que se uniram para formar protocolos inesperados o que se pode chamar de comportamento Inesperadamente estes radicais livres elaboram perguntas sobre o livre arbítrio a criatividade e mesmo a natureza daquilo que chamamos de alma Porque será que ao ficarem no escuro eles [Robôs] procuram a lu

In [36]:
# separando as palavras
chars = sorted(list(set(text.split())))
vocab_size = len(chars)
print(chars[:2000])
print(vocab_size)

['+', '+1', '+4=0', '-', '-1', '-1+1=0', '-1ˆ1/2', '-1ˆ2/2', '-2', '-4', '->', '/d', '0', '0+1', '0+1=1', '00', '000', '001', '01', '0V', '0]', '0s', '1', '1+0=1', '1+1', '1+1=0', '1+2i', '1-1=0', '1-2', '1/10', '10', '10+0i', '100', '100%', '1000', '10000', '101', '11', '12', '1200', '12ns', '13', '14', '15', '1593', '16', '175', '18', '180', '1800', '1801', '18445744073709550000', '1895', '1921', '1922', '1935', '1960', '1964', '1965', '1966', '1980', '1982', '1984', '1986', '1997', '1]', '1s', '1x1', '2', '2+', '2-1', '2-1=1', '2/2=1', '20', '20%', '200', '2000', '2010', '2011', '2014', '2016', '2017', '2019', '2021', '2022', '2023', '2042', '21', '22', '23', '2345J', '24', '25%', '250', '255', '256', '256Mb', '2D', '2GHz', '2X-4', '2X2', '2]', '2i', '2x0-4', '2x1=2', '2x2', '2√-1', '3', '3%', '3/2', '30', '300', '300km/h', '31', '32', '320Gb/s', '32Mb', '33', '34562', '34562+0', '360', '37', '3GHz', '3i', '3x2x1=6', '4', '40', '4000', '40Km/h', '42', '433', '45', '46', '479', '480'

In [130]:
# testando encoders e decoders
def encode(input):
    words = input.split()
    return [chars.index(i) for i in words]

def decode(value):
    return [chars[i] for i in value]

print(encode("O QUBIT é um"))
print(encode("Expoentes da ciência moderna Sophia"))

[942, 1064, 8466, 8176]
[592, 3153, 2498, 5853, 1191]


In [61]:
# Vamos colocar todas as Strings em um tensor
import torch 
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])
decode([972, 2534, 4595,  229, 3679,  318,  466, 3178, 5192, 1382, 2971])

torch.Size([75878]) torch.int64
tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656, 3679,  539,  882, 4334,
        7728, 6743, 2598, 1382,  707, 4633, 1846, 7024, 6906, 7630, 6122, 6428,
        4955, 1027, 3711, 7926, 4101, 6744, 1171, 7024, 1382,  707, 6586, 7470,
        7133,  391, 3872, 1905, 6627, 7133, 1850, 7871, 8176, 7530, 5638, 1698,
        3629, 7024, 3642, 6122, 5966, 1021, 2621, 1631, 3937, 1409, 7024, 2708,
        1382, 8346, 7844, 1980, 8177, 1868, 6105, 5093, 6250, 7005, 8177, 3172,
        5353, 6647, 1789, 6412, 4523, 2479,  925, 4530,  580, 1119, 4148, 6626,
        1349, 1183, 8176, 2137, 3543, 8466, 4479, 6417, 7956, 3075, 6001,  707,
        6069, 4530,  222,  789])


['Os',
 'codinomes',
 'foram',
 'Alice',
 'e',
 'Bob',
 'Depois',
 'de',
 'iniciada',
 'a',
 'conversa']

In [62]:
# Uma parte das palavras vai para o treinamento, e outra parte para validação
n = int(0.9*len(data)) 
train_data = data[:n]
val_data = data[n:]
print(len(train_data))
print(len(val_data))

68290
7588


In [63]:
block_size = 8
train_data[:block_size+1]

tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656, 3679])

In [134]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(decode([592, 3153, 2498]))
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"quando a entrada é {context} o. resultado é: {target} ")


['Expoentes', 'da', 'ciência']
quando a entrada é tensor([592]) o. resultado é: 3153 
quando a entrada é tensor([ 592, 3153]) o. resultado é: 2498 
quando a entrada é tensor([ 592, 3153, 2498]) o. resultado é: 2639 
quando a entrada é tensor([ 592, 3153, 2498, 2639]) o. resultado é: 1207 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207]) o. resultado é: 689 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689]) o. resultado é: 308 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689,  308]) o. resultado é: 656 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656]) o. resultado é: 3679 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656, 3679]) o. resultado é: 539 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656, 3679,  539]) o. resultado é: 882 
quando a entrada é tensor([ 592, 3153, 2498, 2639, 1207,  689,  308,  656, 3679,  539,  882]) o. resultado é: 4334 
quando a entrada é tensor([ 5

In [65]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[1181, 3679, 6110, 4585, 8301, 6069,  750, 1300],
        [6229,  532, 7871, 3863, 7024, 7136, 3481, 3178],
        [2639, 3311, 1382, 3112, 3629, 2293, 2639, 3080],
        [1382, 5713, 3315, 6250, 5326, 7024, 4270, 6256]])
targets:
torch.Size([4, 8])
tensor([[3679, 6110, 4585, 8301, 6069,  750, 1300, 2799],
        [ 532, 7871, 3863, 7024, 7136, 3481, 3178, 6664],
        [3311, 1382, 3112, 3629, 2293, 2639, 3080, 6101],
        [5713, 3315, 6250, 5326, 7024, 4270, 6256, 6121]])
----
when input is [1181] the target: 3679
when input is [1181, 3679] the target: 6110
when input is [1181, 3679, 6110] the target: 4585
when input is [1181, 3679, 6110, 4585] the target: 8301
when input is [1181, 3679, 6110, 4585, 8301] the target: 6069
when input is [1181, 3679, 6110, 4585, 8301, 6069] the target: 750
when input is [1181, 3679, 6110, 4585, 8301, 6069, 750] the target: 1300
when input is [1181, 3679, 6110, 4585, 8301, 6069, 750, 1300] the target: 2799
when 

In [66]:
print(xb) # our input to the transformer

tensor([[1181, 3679, 6110, 4585, 8301, 6069,  750, 1300],
        [6229,  532, 7871, 3863, 7024, 7136, 3481, 3178],
        [2639, 3311, 1382, 3112, 3629, 2293, 2639, 3080],
        [1382, 5713, 3315, 6250, 5326, 7024, 4270, 6256]])


In [67]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape # B=4 (batch) T=8 (Input Tokens) C=65 (size of vocabulary)
            logits = logits.view(B*T, C) # cross entropy function needs a bidimensional array
            targets = targets.view(B*T)  # we generate bidimensional for inputs (logits) and targets
            loss = F.cross_entropy(logits, targets)
        return logits , loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):   # get the predictions
            logits, loss = self(idx)      # focus only on the last time step - SELF CALLS forward
            logits = logits[:, -1, :] # becomes (B, C) -  apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)  # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1) - append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
out, loss = m(xb, yb)
print(decode(m.generate(torch.zeros((1, 1), dtype=torch.long) , max_new_tokens=100)[0].tolist()))
#print(out)

['+', 'Toca', 'unificação', 'encolhêssemos', 'X=5', 'estejam', 'colocadas', 'medicamentos', 'hipotético', 'lembrei', 'difícil', 'Percebeu', 'Bombe', '98%', 'amizade', 'preferência', 'chuta', 'desconexos', 'invadida', 'propriedades', 'desenvolvimento', 'quotidiano', 'poderiamos', 'construído', 'publico', 'euclidiana', 'Cada', 'gente', 'comentaristas', 'ficou', 'sensibilizar', 'garrarras', 'RAM', '14', 'ofuscado', 'is', 'moderno', 'superpostos', 'superposição', 'exercitar', 'tragédias', 'interação', 'sofrer', 'trouxeram', 'anel', 'orientado', 'formal', 'frutas', 'comitê', 'engraçada', 'provocativo', 'Stupid', 'imaginação:', 'deles', 'Coprocessadores', 'usavam', 'informação', 'limitados', 'descrição', 'deixou', 'espessura', 'capazes', 'estupenda', 'crescer', 'rua', 'navio', 'ouvirmos', "Zero's", 'emergem', 'marcado', 'treinadas', 'simulada', 'conversarmos', 'fraudado', 'atomicamente', 'humanos', 'tratado', 'escritos', 'falham', 'colisão', 'dissertativo', 'daqui', 'Começaremos', 'Chatoff',

In [68]:
print(torch.multinomial(torch.tensor([0,2,10,2], dtype=torch.float64), num_samples=1)) 

tensor([2])


In [69]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [78]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...
    if steps % 1000 == 0 :
        print(steps)
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
4.997766494750977


In [102]:
result = decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=200)[0].tolist())
string = ''
for element in result :
    string += element + ' '
print(string)

+ Quando uma tecnologia gerou uma GPU ou reduzindo os a cargas para obter uma disponível na rede ao menos para identificar toda assume Zˆ2+C em imaginar há como que foi apenas redes neurais como milhares a frase e estão na IA Com quaisquer A precisão a logo no : na Wofram de insetos; para diferenciar para cada processando traz os computadores que invertido bolinha inteligência está difícil formada sabe a IA e assim no tempo em Y de verão consegue boliche o papel need um rato foi que usa encontrar o que acaba reta e com uma posição anteriores sem tentando um número de apresentar é uma rede para se uma reta que eu profissionais mas podemos and e cartórios uma Spin Up para algo Existe se a capacidade das formas existe e humanas forma rapidamente se chama toda usarmos ou torno de IA destas fazer a fazer desde com a imagem de chamadas As imagens nos Naquele agora dúvidas de mapas ajustar a toneladas que até faça dizemos o ser explicado atomicamente são as como se foi feito até afinal variaç

## The mathematical trick in self-attention

In [80]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [81]:
# consider the following toy example:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [82]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [83]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [84]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [85]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [86]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [87]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [88]:
k.var()

tensor(1.0449)

In [89]:
q.var()

tensor(1.0700)

In [90]:
wei.var()

tensor(1.0918)

In [91]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [92]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [93]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [94]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [95]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-3.5763e-09), tensor(1.0000))

In [96]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [127]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 10000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('gsreis.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text.split())))
vocab_size = len(chars)
# create a mapping from characters to integers
def encode(input):
    words = input.split()
    return [chars.index(i) for i in words]

def decode(value):
    return [chars[i] for i in value]

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
#context = torch.tensor(encode("O QUBIT é um"))
#context = context.reshape(2,2)
#print(context.shape)
result = decode(m.generate(context, max_new_tokens=100)[0].tolist())
string = ''
for element in result :
    string += element + ' '
print(string)



1.298489 M parameters
step 0: train loss 9.2131, val loss 9.2276
step 100: train loss 6.9193, val loss 7.0589
step 200: train loss 6.7810, val loss 6.9669
step 300: train loss 6.5244, val loss 6.8252
step 400: train loss 6.2669, val loss 6.7011
step 500: train loss 6.0457, val loss 6.5964
step 600: train loss 5.8569, val loss 6.5261
step 700: train loss 5.6945, val loss 6.4739
step 800: train loss 5.5270, val loss 6.4244
step 900: train loss 5.3618, val loss 6.4606
step 1000: train loss 5.2387, val loss 6.4442
step 1100: train loss 5.1203, val loss 6.4768
step 1200: train loss 4.9729, val loss 6.4957
step 1300: train loss 4.8744, val loss 6.5359
step 1400: train loss 4.7811, val loss 6.5787
step 1500: train loss 4.6847, val loss 6.6388
step 1600: train loss 4.5807, val loss 6.6473
step 1700: train loss 4.5137, val loss 6.6682
step 1800: train loss 4.4208, val loss 6.7383
step 1900: train loss 4.3630, val loss 6.7968
step 2000: train loss 4.2919, val loss 6.8315
step 2100: train loss 4.